---

- name: Determine if oracle java repository needs to be enabled
  shell: /usr/sbin/subscription-manager repos --list-enabled | grep Oracle
  register: repo_status
  failed_when: "repo_status.rc > 1"
  changed_when: "repo_status.rc == 1"

- name: Enable RHEL third party oracle java repository.
  command: /usr/sbin/subscription-manager repos --enable={{ java_reponame }}
  when: repo_status.rc == 1

- name: Install the Oracle JDK
  yum: name={{ java_package }} state=latest
